from datetime import datetime
from core.timeline import build_timeline


def format_timestamp(ts):
    try:
        return datetime.fromtimestamp(float(ts)).strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return str(ts)


def incident_type(incident):
    reasons = " ".join(incident.get("reasons", [])).lower()

    if "brute" in reasons:
        return "SSH Brute Force"

    if "suricata" in reasons:
        return "Network Intrusion Attempt"

    return "Suspicious Activity"


def recommendations(incident):
    reasons = " ".join(incident.get("reasons", [])).lower()

    recs = []

    if "brute" in reasons:
        recs.extend([
            "Enable SSH key-based authentication",
            "Disable direct root SSH login",
            "Enable MFA where possible",
            "Review successful login activity",
            "Block or rate-limit offending IP addresses"
        ])

    if "suricata" in reasons:
        recs.extend([
            "Inspect affected host",
            "Review IDS alerts for related activity",
            "Check firewall logs",
            "Validate exposed services"
        ])

    if not recs:
        recs.append("Continue monitoring activity")

    return recs


def analyst_assessment(risk):
    if risk == "CRITICAL":
        return (
            "Multiple high-confidence indicators suggest active malicious "
            "activity requiring immediate response."
        )

    if risk == "HIGH":
        return (
            "Indicators strongly suggest hostile activity. "
            "Immediate investigation is recommended."
        )

    if risk == "MEDIUM":
        return (
            "Suspicious activity observed. Further analysis is recommended."
        )

    return "Low-risk activity observed."


def generate_report(incident):
    print("🔥 NEW REPORT ENGINE LOADED")

    timeline = build_timeline(incident["events"])

    report = []

    report.append("=" * 60)
    report.append("SENTINELFORGE INCIDENT INVESTIGATION REPORT")
    report.append("=" * 60)

    report.append("")
    report.append(f"Incident Type : {incident_type(incident)}")
    report.append(f"Source IP     : {incident['ip']}")
    report.append(f"Severity      : {incident['risk']}")
    report.append(f"Risk Score    : {incident['risk_score']}/100")
    report.append(f"Event Count   : {incident['event_count']}")

    report.append("")
    report.append("ATT&CK MAPPING")

    for m in incident.get("mitre", []):
        report.append(f" - {m}")

    report.append("")
    report.append("DETECTION REASONS")

    for reason in incident.get("reasons", []):
        report.append(f" - {reason}")

    report.append("")
    report.append("TIMELINE")

    for e in timeline:
        ts = format_timestamp(e.get("timestamp"))
        report.append(
            f" {ts} | {e.get('event')} | {e.get('source')}"
        )

    report.append("")
    report.append("ANALYST ASSESSMENT")
    report.append(analyst_assessment(incident["risk"]))

    report.append("")
    report.append("RECOMMENDED ACTIONS")

    for rec in recommendations(incident):
        report.append(f" - {rec}")

    report.append("")
    report.append("Generated by SentinelForge AI SOC Platform")

    return "\n".join(report)
